# Generated by Django 2.2.2 on 2019-06-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pheonixapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='url',
            field=models.TextField(default='SOME STRING', max_length=21845),
        ),
    ]
