# Generated by Django 2.2.2 on 2019-06-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pheonixapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ls',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='SOME STRING', max_length=100)),
            ],
        ),
    ]
