# Generated by Django 2.2.2 on 2019-06-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pheonixapp', '0002_ls'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ls',
        ),
        migrations.AlterField(
            model_name='profile',
            name='url',
            field=models.TextField(default='SOME STRING', max_length=21845),
        ),
    ]
