# Generated by Django 2.2.2 on 2019-06-19 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pheonixapp', '0002_auto_20190619_0810'),
    ]

    operations = [
        migrations.DeleteModel(
            name='List',
        ),
    ]
