# Generated by Django 2.2.2 on 2019-06-13 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pheonixapp', '0002_ls'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ls',
        ),
    ]
