# Generated by Django 2.2.2 on 2019-06-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pheonixapp', '0002_auto_20190609_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='title',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
