# Generated by Django 2.2.2 on 2019-06-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pheonixapp', '0003_blogs_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='country',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
