# Generated by Django 2.2.2 on 2019-06-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pheonixapp', '0004_blogs_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='image',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
