# Generated by Django 2.2.2 on 2019-06-19 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pheonixapp', '0005_list_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='done',
        ),
    ]
