# Generated by Django 2.2.2 on 2019-06-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pheonixapp', '0005_blogs_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='image',
            field=models.CharField(default='SOME STRING', max_length=500),
        ),
    ]
