# Generated by Django 2.2.2 on 2019-06-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pheonixapp', '0006_auto_20190610_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='SOME STRING', max_length=100)),
                ('country', models.EmailField(default='SOME STRING', max_length=100)),
                ('phone', models.CharField(default='SOME STRING', max_length=50)),
                ('image', models.CharField(default='SOME STRING', max_length=100)),
                ('rating', models.CharField(default='SOME STRING', max_length=200)),
                ('price', models.CharField(default='SOME STRING', max_length=200)),
            ],
        ),
    ]
