# Generated by Django 2.2.2 on 2019-06-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pheonixapp', '0009_hotels_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='link',
            field=models.CharField(default='SOME STRING', max_length=900),
        ),
    ]
